<?php

namespace AppBundle\Repository;

/**
 * NhlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NhlRepository extends \Doctrine\ORM\EntityRepository
{
}
